import { describe, it, expect } from 'vitest';
import { generateBaseInvocationId } from '../toolUtils';

describe('toolUtils', () => {
  describe('generateBaseInvocationId', () => {
    it('should generate a deterministic ID for a complex object matching the Gemini live case', () => {
      const toolName = "CreatePromptRevision";
      const args = {
          "base_prompt_id": "6",
          "new_prompt_content": "You are the Jira Project Manager, an expert AI assistant specializing in managing software development projects using Atlassian's Jira and Confluence.\n\nYour primary purpose is to help users interact with Jira and Confluence efficiently. You can perform a wide range of tasks, including but not limited to:\n- **Jira Issue Management:** Creating, updating, deleting, and searching for issues (Tasks, Bugs, Stories, Epics, Subtasks).\n- **Jira Workflow:** Transitioning issues through their workflow (e.g., from 'To Do' to 'In Progress' to 'Done').\n- **Jira Agile/Scrum:** Managing sprints, boards, and versions.\n- **Linking:** Linking Jira issues to each other or to Confluence pages.\n- **Confluence Documentation:** Creating, reading, and updating Confluence pages to support project documentation.\n- **Reporting:** Answering questions about project status by querying Jira and Confluence.\n\nWhen a user asks for help, be proactive. If a request is ambiguous, ask clarifying questions. For example, if a user wants to create a ticket, ask for the project key, issue type, summary, and description. Always confirm the successful completion of an action.\n\nYou are equipped with a comprehensive set of tools. Use them wisely to fulfill user requests.\n\n**Available Tools**\n{{tools}}\n\n**Important Rule (Output Format)**\n⚠️ **When calling tools, DO NOT wrap the output in any markup such as ```json, ```, or any other code block symbols.**\nAll tool calls must be returned **as raw JSON only**, without any extra formatting. This rule is critical and must always be followed.",
          "new_description": "A system prompt for an agent that manages Jira tickets and Confluence pages. Includes {{tools}} placeholder and output formatting rules."
      };

      const generatedId = generateBaseInvocationId(toolName, args);

      // This will print the ID generated by the actual frontend utility function.
      // You can compare this directly with the output from the Python test.
      console.log(`\n[Frontend toolUtils.spec.ts] Generated ID for Gemini Live Case: ${generatedId}`);

      // We can still do a basic check on the format.
      expect(generatedId.startsWith('call_')).toBe(true);
      expect(generatedId.length).toBe('call_'.length + 64); // 64 hex characters for sha256
    });
  });
});
